spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
  
spring:
  profiles: dev
  application:
    name: deptspringcloud-config-spring-dev
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka
    
---    
spring:
  profiles:
    active:
    - test
---
server:
  port: 8202
  
spring:
  profiles: test
  application:
    name: deptspringcloud-config-spring-test
    
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:7001/eureka